language: c
sudo: true
dist: bionic
before_install:
          - wget "https://github.com/devkitPro/pacman/releases/latest/download/devkitpro-pacman.deb" -O dkp-pacman.deb
          - export DEVKITPRO=/opt/devkitpro
          - export DEVKITARM=${DEVKITPRO}/devkitARM

install:
          - sudo dpkg -i dkp-pacman.deb
          - sudo dkp-pacman -S --noconfirm 3ds-dev 3ds-libxmp

script:
  - make
